name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-2019
    env:
      libraryName: libredwg
      cmakeInstallationPath: libredwg-installation
      tagName: 0.12.5 #target tag
      mingwTargetZip: libredwg-${{ github.ref_name }}-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - name: check mingw version
        run: gcc --version
        
      - name: git clone
        shell: cmd
        run: git clone --recursive https://github.com/LibreDWG/libredwg.git && cd libredwg && git checkout ${{ env.tagName }}

      - name: cmake
        shell: cmd
        run: cd libredwg && cmake.exe -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DLIBREDWG_LIBONLY=ON -DCMAKE_INSTALL_PREFIX="build/${{ env.cmakeInstallationPath }}" -B./build
        
      - name: dirty work - remove alloca.h detection
        shell: cmd
        run: 'cd libredwg\build\src && aria2c https://github.com/dirkarnez/textfile-direct-modifier/releases/download/v1.0.0/textfile-direct-modifier-v1.0.0.zip && 7z.exe x textfile-direct-modifier-v1.0.0.zip && textfile-direct-modifier.exe --source=config.h --target=config.h --old="#define HAVE_ALLOCA 1" --new="/* #define HAVE_ALLOCA 1*/" && textfile-direct-modifier.exe --source=config.h --target=config.h --old="#define HAVE_ALLOCA_H 1" --new="/* #define HAVE_ALLOCA_H 1 */"' 
        
      - name: cmake build and install
        shell: cmd
        run: cd libredwg\build && cmake --build . && cmake --install . 
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "libredwg/build/${{ env.cmakeInstallationPath }}"
          filename: "${{ env.mingwTargetZip }}"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "libredwg/build/${{ env.cmakeInstallationPath }}/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
